B2BPortal/Areas/Admin/Controllers/BulkInviteController.cs
using AzureB2BInvite.Utils;
using B2BPortal.Infrastructure;
using B2BPortal.Infrastructure.Filters;
using System;
using System.Collections.Generic;
using System.IdentityModel.Claims;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace B2BPortal.Areas.Admin.Controllers
{
    [AuthorizedInviter]
    public class BulkInviteController : Controller
    {
        // GET: Admin/BulkInvite
        public async Task<ActionResult> Index()
        {
            var res = new List<SelectListItem>();
            var templates = (await TemplateUtilities.GetTemplates()).ToList();

            res.AddRange(templates.Select(t => new SelectListItem { Selected = (t.TemplateName == "Default"), Text = t.TemplateName, Value = t.Id }));
            ViewBag.Templates = res;
            return View();
        }

        public ActionResult Status()
        {
            return View();
        }
    }
}

B2BPortal/Areas/Admin/Controllers/InviteTemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using B2BPortal.Infrastructure;
using B2BPortal.Infrastructure.Filters;
using B2BPortal.Data;
using AzureB2BInvite;
using AzureB2BInvite.Utils;

namespace B2BPortal.Areas.Admin.Controllers
{
    [AuthorizedInviter]
    public class InviteTemplateController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var templates = await TemplateUtilities.GetTemplates();
            if (templates.Count() == 0)
            {
                templates = await TemplateUtilities.InitializeDefaultTemplate(User.Identity.GetEmail());
            }
            return View(templates);
        }

        public async Task<ActionResult> Edit(string id)
        {
            InviteTemplate template;
            if (id == null)
            {
                ViewBag.Operation = "New";
                template = new InviteTemplate();
            }
            else
            {
                ViewBag.Operation = "Edit";
                template = await TemplateUtilities.GetTemplate(id);
            }
            return View(template);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(InviteTemplate template)
        {
            try
            {
                await TemplateUtilities.DeleteTemplate(template);
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Operation = "Delete";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Save(InviteTemplate template)
        {
            if (ModelState.IsValid)
            {
                //check for subject template if smtp
                if (Settings.UseSMTP)
                {
                    if (string.IsNullOrEmpty(template.SubjectTemplate))
                    {
                        ModelState.AddModelError("SubjectTemplate", "With SMTP enabled, the subject template is required.");
                        return View("Edit", template);
                    }
                }
                try
                {
                    template.TemplateAuthor = User.Identity.GetEmail();
                    if (template.Id == null)
                    {
                        template = await TemplateUtilities.AddTemplate(template);
                    }
                    else
                    {
                        template = await TemplateUtilities.UpdateTemplate(template);
                    }
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View("Edit", template);
                }
            }
            return View("Edit", template);
        }
    }
}

B2BPortal/Areas/Admin/Controllers/PreApprovalController.cs
using AzureB2BInvite.Models;
using B2BPortal.Data;
using B2BPortal.Infrastructure.Filters;
using B2BPortal.Infrastructure;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AzureB2BInvite;
using AzureB2BInvite.Utils;
using Microsoft.Graph;
using System.IdentityModel.Claims;
using B2BPortal.Common.Models;

namespace B2BPortal.Areas.Admin.Controllers
{
    [AuthorizedInviter]
    public class PreApprovalController : AsyncController
    {
        private List<InviteTemplate> _templates;

        public PreApprovalController()
        {
            var task = Task.Run(async () => {
                _templates = (await TemplateUtilities.GetTemplates()).ToList();
            });
            task.Wait();
        }
        private IEnumerable<SelectListItem> GetTemplates(string templateId)
        {
            var res = new List<SelectListItem>();
            res.AddRange(_templates.Select(t => new SelectListItem { Selected = ((templateId==null) ? (t.TemplateName == "Default") : (t.Id == templateId)), Text = t.TemplateName, Value = t.Id }));
            return res;
        }

        public async Task<ActionResult> Index()
        {
            IEnumerable<PreAuthDomain> domains = null;
            try
            {
                domains = await PreAuthDomain.GetDomains();
            }
            catch (Exception)
            {
                //see if this domain needs the group object updated
                domains = await PreAuthDomain.RefreshAllPreAuthGroupData();
            }
            return View(domains);
        }

        [HttpPost]
        public async Task<ActionResult> Create(PreAuthDomain domain)
        {
            ViewBag.Templates = GetTemplates(domain.InviteTemplateId);

            if (ModelState.IsValid)
            {
                try
                {
                    domain.AuthUser = User.Identity.GetEmail();
                    var doc = await PreAuthDomain.AddDomain(domain);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View("Edit", domain);
                }
            }

            return View("Edit", domain);
        }

        public async Task<ActionResult> Edit(string id)
        {
            PreAuthDomain domain;
            if (id == null)
            {
                ViewBag.Operation = "Create";
                domain = new PreAuthDomain();
                domain.DomainRedemptionSettings.InviteRedirectUrl = string.Format("https://myapps.microsoft.com/{0}", Settings.Tenant);
                domain.DomainRedemptionSettings.InviterResponseEmailAddr = User.Identity.GetClaim(ClaimTypes.Email);
            }
            else
            {
                ViewBag.Operation = "Edit";
                domain = await PreAuthDomain.GetDomain(id);
            }

            ViewBag.Templates = GetTemplates(domain.InviteTemplateId);
            return View(domain);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(PreAuthDomain domain)
        {
            ViewBag.Templates = GetTemplates(domain.InviteTemplateId);

            if (ModelState.IsValid)
            {
                try
                {
                    domain.AuthUser = User.Identity.GetEmail();

                    if (domain.Id == null)
                    {
                        domain = await PreAuthDomain.AddDomain(domain);
                    }
                    else
                    {
                        domain = await PreAuthDomain.UpdateDomain(domain);
                    }

                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Operation = "Edit";
                    return View(domain);
                }
            }
            return View(domain);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(PreAuthDomain domain)
        {
            try
            {
                await PreAuthDomain.DeleteDomain(domain);
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Operation = "Delete";
                return RedirectToAction("Index");
            }
        }
    }
}

B2BPortal/Areas/Admin/Controllers/SiteConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using B2BPortal.Infrastructure;
using B2BPortal.Infrastructure.Filters;
using AzureB2BInvite.Models;
using AzureB2BInvite.Utils;
using B2BPortal.Data;
using AzureB2BInvite;
using AzureB2BInvite.Rules;

namespace B2BPortal.Areas.Admin.Controllers
{
    [AuthorizedInviter]
    public class SiteConfigController : Controller
    {
        private List<InviteTemplate> _templates;

        public SiteConfigController()
        {
            var task = Task.Run(async () => {
                _templates = (await TemplateUtilities.GetTemplates()).ToList();
            });
            task.Wait();
        }

        private IEnumerable<SelectListItem> GetTemplates(string templateId)
        {
            var res = new List<SelectListItem>();
            res.AddRange(_templates.Select(t => new SelectListItem { Selected = (t.Id == templateId), Text = t.TemplateName, Value = t.Id }));
            return res;
        }

        public async Task<ActionResult> Index()
        {
            var config = await SiteConfigRules.GetCurrConfig();
            if (config == null)
            {
                _templates = (await TemplateUtilities.InitializeDefaultTemplate(User.Identity.GetEmail())).ToList();
                var template = _templates.First();

                config = new SiteConfig
                {
                    InviteTemplateContent = template,
                    InviteTemplateId = template.Id
                };
            }

            ViewBag.Templates = GetTemplates(config.InviteTemplateId);

            return View("Edit", config);
        }

        public async Task<ActionResult> List()
        {
            var configs = await SiteConfigRules.GetAllConfigs();
            return View(configs);
        }

        public async Task<ActionResult> Details(string id)
        {
            var config = await SiteConfigRules.GetConfig(id);
            ViewBag.Templates = GetTemplates(config.InviteTemplateId);
            return View(config);
        }

        public async Task<ActionResult> Edit(string id)
        {
            ViewBag.Operation = "Edit";
            var config = await SiteConfigRules.GetConfig(id);
            ViewBag.Templates = GetTemplates(config.InviteTemplateId);

            return View(config);
        }

        public async Task<ActionResult> HistoryDetail(string id)
        {
            var config = await SiteConfigRules.GetConfig(id);
            ViewBag.Templates = GetTemplates(config.InviteTemplateId);

            return View(config);
        }

        [HttpPost]
        public async Task<ActionResult> Save(SiteConfig config)
        {
            ViewBag.Templates = GetTemplates(config.InviteTemplateId);

            if (ModelState.IsValid)
            {
                try
                {
                    config.ConfigAuthor = User.Identity.GetEmail();
                    config = await SiteConfigRules.SetNewConfig(config);
                    Settings.SiteConfigReady = true;
                    Settings.CurrSiteConfig = config;

                    //refresh invitation settings
                    MailSender.MailFrom = Settings.CurrSiteConfig.SiteRedemptionSettings.InviterResponseEmailAddr;

                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Error = "An error occured saving your config, please check the error logs and try again.";
                    return View("Edit", config);
                }
            }
            return View("Edit", config);
        }
    }
}

B2BPortal/Views/Shared/PreAuthError.cshtml
@using AzureB2BInvite

@{
    ViewBag.Title = "PreAuthError";
}

<h2>Invalid Credentials</h2>
<p>
    Sorry, you still appear to be authenticated using the "Pre-Auth" credentials from your home tenant.
</p>
<p>
    To manage your guest profile in the @Settings.CurrSiteConfig.InvitingOrg organization,
    please @Html.ActionLink("logout", "Signout", "Account") to continue.
</p>

B2BPortal/Views/Shared/_Layout.cshtml
@using B2BPortal.Infrastructure
@using AzureB2BInvite
@{ 
    var siteName = (Settings.CurrSiteConfig != null && !string.IsNullOrEmpty(Settings.CurrSiteConfig.InvitingOrg)) ? Settings.CurrSiteConfig.InvitingOrg : "B2B Portal";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @siteName</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
    @if (User.Identity.IsAuthenticated)
    {
        <script type="text/javascript">
        window.loggedInUser = "@User.Identity.Name";
        </script>
    }
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span id="collapsedLoader" class="ui-loader glyphicon glyphicon-refresh glyphicon-refresh-animate"></span>
                @if (Settings.Branding.TileLogo.Image.Length > 0)
                {
                    <img style="width:50px;margin-right:4px;" class="pull-left" src="/home/branding/3" />
                }

                @Html.ActionLink(siteName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Sign Up", "Index", "Home", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { })</li>
                    @if (User.Identity.IsInAnyRole(Settings.InviterRoleNames))
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Home", new { area="admin" })"><span class='glyphicon glyphicon-ok pull-left'></span> Approve Requests</a></li>
                            <li><a href="@Url.Action("Index", "PreApproval", new { area="admin" })"><span class='glyphicon glyphicon-heart pull-left'></span> Manage Domains</a></li>
                            <li><a href="@Url.Action("Index", "InviteTemplate", new { area="admin" })"><span class='glyphicon glyphicon-envelope pull-left'></span> Manage Mail Templates</a></li>
                            <li><a href="@Url.Action("Index", "BulkInvite", new { area = "admin" })"><span class='glyphicon glyphicon-user pull-left'></span> Batch Invitations</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("Index", "SiteConfig", new { area="admin" })"><span class='glyphicon glyphicon-cog pull-left'></span> Site Config</a></li>
                        </ul>
                    </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>